python train_homo.py \
    --dataset citeseer_lcc \
    --seed 123 \
    --learning_rate_train 0.001 \
    --learning_rate_adv 0.0005 \
    --num_hidden 128 \
    --num_proj_hidden 128 \
    --num_edge_hidden 128 \
    --activation prelu \
    --base_model GCNConv \
    --num_layers 2 \
    --tau 0.9 \
    --num_epochs 150 \
    --reg_lambda 0.9 \
    --gpu_id 0
